name: Workflow Basico

on:
  push:
  workflow_dispatch:

jobs:
  CorreWorkflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Echo en Workflow
        run: echo "Esta es la ejecución de mi primer workflow"
